package service

import (
	"path/filepath"
	"testing"

	"gost-panel/internal/dto"
	"gost-panel/internal/errors"
	"gost-panel/internal/model"
	"gost-panel/internal/repository"

	"github.com/glebarez/sqlite"
	"gorm.io/gorm"
	gormlogger "gorm.io/gorm/logger"
)

func newObserverTestDB(t *testing.T) *gorm.DB {
	t.Helper()

	db, err := gorm.Open(
		sqlite.Open(filepath.Join(t.TempDir(), "observer.db")),
		&gorm.Config{Logger: gormlogger.Discard},
	)
	if err != nil {
		t.Fatalf("打开测试数据库失败: %v", err)
	}
	t.Cleanup(func() {
		if sqlDB, err := db.DB(); err == nil {
			_ = sqlDB.Close()
		}
	})
	if err := db.AutoMigrate(
		&model.SystemConfig{}, &model.GostNode{}, &model.GostRule{}, &model.GostTunnel{},
	); err != nil {
		t.Fatalf("迁移失败: %v", err)
	}
	return db
}

// TestObserverToken_AutoGeneratedAndStable 验证上报令牌会自动生成且保持稳定。
// 从旧版本升级上来的实例数据库里没有该字段，必须能自动补齐，
// 否则所有节点的流量上报都会被新的鉴权挡掉。
func TestObserverToken_AutoGeneratedAndStable(t *testing.T) {
	db := newObserverTestDB(t)
	repo := repository.NewSystemConfigRepository(db)

	// 模拟旧版本遗留：配置存在但没有令牌
	if err := db.Create(&model.SystemConfig{ID: 1, SiteTitle: "Gost Panel"}).Error; err != nil {
		t.Fatalf("构造旧数据失败: %v", err)
	}

	cfg, err := repo.Get()
	if err != nil {
		t.Fatalf("读取配置失败: %v", err)
	}
	if len(cfg.ObserverToken) != 64 { // 32 字节 hex
		t.Fatalf("期望自动生成 64 位十六进制令牌，实际 %q", cfg.ObserverToken)
	}

	// 再次读取必须返回同一个令牌，否则已下发到节点的地址会立即失效
	cfg2, err := repo.Get()
	if err != nil {
		t.Fatalf("二次读取失败: %v", err)
	}
	if cfg2.ObserverToken != cfg.ObserverToken {
		t.Errorf("令牌在两次读取间发生变化: %q -> %q", cfg.ObserverToken, cfg2.ObserverToken)
	}
}

// TestVerifyReportToken 覆盖上报鉴权的拒绝与放行两条路径
func TestVerifyReportToken(t *testing.T) {
	db := newObserverTestDB(t)
	svc := NewObserverService(db)

	cfg, err := repository.NewSystemConfigRepository(db).Get()
	if err != nil {
		t.Fatalf("读取配置失败: %v", err)
	}

	cases := []struct {
		name    string
		token   string
		wantErr error
	}{
		{"空令牌", "", errors.ErrObserverTokenInvalid},
		{"错误令牌", "deadbeef", errors.ErrObserverTokenInvalid},
		{"正确令牌前缀", cfg.ObserverToken[:len(cfg.ObserverToken)-1], errors.ErrObserverTokenInvalid},
		{"正确令牌", cfg.ObserverToken, nil},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if err := svc.VerifyReportToken(tc.token); err != tc.wantErr {
				t.Errorf("期望 %v，实际 %v", tc.wantErr, err)
			}
		})
	}
}

// TestHandleReport_UpdatesStats 验证带令牌放行后，上报的统计确实写入了规则。
// 这是"只测了拒绝路径、没测放行路径"最容易漏掉的回归。
func TestHandleReport_UpdatesStats(t *testing.T) {
	db := newObserverTestDB(t)
	svc := NewObserverService(db)

	nodeID := uint(1)
	if err := db.Create(&model.GostNode{ID: nodeID, Name: "n1", Address: "127.0.0.1", Port: 39000}).Error; err != nil {
		t.Fatalf("创建节点失败: %v", err)
	}
	if err := db.Create(&model.GostRule{ID: 7, Name: "r1", Type: model.RuleTypeForward, NodeID: &nodeID, ListenPort: 1234}).Error; err != nil {
		t.Fatalf("创建规则失败: %v", err)
	}

	err := svc.HandleReport(&dto.ObserverReportReq{Events: []dto.ObserverEvent{{
		Kind:    "service",
		Type:    "stats",
		Service: "rule-7",
		Stats:   &dto.ObserverStats{InputBytes: 1000, OutputBytes: 2000, TotalConns: 3},
	}}})
	if err != nil {
		t.Fatalf("处理上报失败: %v", err)
	}

	var rule model.GostRule
	if err := db.First(&rule, 7).Error; err != nil {
		t.Fatalf("查询规则失败: %v", err)
	}
	if rule.InputBytes != 1000 || rule.OutputBytes != 2000 {
		t.Errorf("统计未写入: in=%d out=%d", rule.InputBytes, rule.OutputBytes)
	}
}

// TestParseServiceID 回归：非法服务名不得被解析成 ID 0 后写入数据库
func TestParseServiceID(t *testing.T) {
	cases := []struct {
		serviceName string
		prefix      string
		wantID      uint
		wantErr     bool
	}{
		{"rule-7", "rule-", 7, false},
		{"relay-tunnel-42", "relay-tunnel-", 42, false},
		{"rule-abc", "rule-", 0, true},                  // 旧实现会静默得到 0
		{"rule-", "rule-", 0, true},                     // 旧实现会静默得到 0
		{"rule-0", "rule-", 0, true},                    // ID 0 不是合法主键
		{"rule--1", "rule-", 0, true},                   // 负数
		{"rule-99999999999999999999", "rule-", 0, true}, // 溢出
	}

	for _, tc := range cases {
		t.Run(tc.serviceName, func(t *testing.T) {
			var id uint
			err := parseServiceID(tc.serviceName, tc.prefix, &id)
			if tc.wantErr {
				if err == nil {
					t.Errorf("期望报错，实际解析出 id=%d", id)
				}
				return
			}
			if err != nil {
				t.Fatalf("非预期错误: %v", err)
			}
			if id != tc.wantID {
				t.Errorf("期望 id=%d，实际 %d", tc.wantID, id)
			}
		})
	}
}
